### ISSUE TITLE
[FEA]: OT use case

### ISSUE THREAD

**Issue by gbatmaz** [nv-morpheus/morpheus-experimental#36]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem this feature solves

A model that works on a power system dataset for operational technology use case

### Describe your ideal solution

XGBoost multiclass classifier

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/morpheus-experimental/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by tzemicheal** [comment]
This is closed by PR #35
