### ISSUE TITLE
[BUG]: cuDF broken in container

### ISSUE THREAD

**Issue by efajardo-nv** [nv-morpheus/morpheus-experimental#48]
### Version

23.07

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

Get the following error when importing `cudf` in container:
```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/mor_exp/lib/python3.8/site-packages/cudf/__init__.py", line 99, in <module>
    patch_numba_codegen_if_needed()
  File "/opt/conda/envs/mor_exp/lib/python3.8/site-packages/ptxcompiler/patch.py", line 256, in patch_numba_codegen_if_needed
    raise RuntimeError(msg)
RuntimeError: Cannot patch Numba: version 0.57.0 should not be patched. Set the environment variable NUMBA_CUDA_ENABLE_MINOR_VERSION_COMPATIBILITY=1 instead. See https://numba.readthedocs.io/en/stable/cuda/minor_version_compatibility.html for more details.
```

### Minimum reproducible example

```shell
1. ./docker/build_container.sh
2. ./docker/run_container.sh
3. python
4. import cudf
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/morpheus-experimental/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @efajardo-nv!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the meantime, feel free to add any relevant information to this issue.
