### ISSUE TITLE
Asset Clustering using Graph Neural Networks

### ISSUE THREAD

**Issue by divyanshjain** [nv-morpheus/morpheus-experimental#59]
- Request to create a pull request for Asset Clustering using Graph Neural Networks.

**Comment by jarmak-nv** [comment]
Hi @divyanshjain!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the meantime, feel free to add any relevant information to this issue.

**Comment by raykallen** [comment]
Hi @divyanshjain, yes please make a PR for asset clustering using GNN
